# -*- coding: utf-8 -*-
"""training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-KMB97LD1A_XJTMvc0y7wG_QUlDjXk1k
"""

!git clone  https://github.com/tensorflow/models

from google.colab import drive
drive.mount('/content/drive',  force_remount=True)

!pip install pip==21.3.1

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/models/research/
# protoc object_detection/protos/*.proto --python_out=.
# cp object_detection/packages/tf2/setup.py .
# python -m pip install .

!python /content/drive/MyDrive/stella_mb2-master/script_dataset/prepareLabelMap.py

!python /content/drive/MyDrive/stella_mb2-master/script_dataset/generate_tfrecord.py -x /content/drive/MyDrive/dataset/train -l /content/drive/MyDrive/stella_mb2-master/labels_map.pbtxt -o /content/drive/MyDrive/dataset/train.record

!python /content/drive/MyDrive/stella_mb2-master/script_dataset/generate_tfrecord.py -x /content/drive/MyDrive/dataset/val -l /content/drive/MyDrive/stella_mb2-master/labels_map.pbtxt -o /content/drive/MyDrive/dataset/val.record

!wget http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz

!python /content/drive/MyDrive/stella_mb2-master/updateConfig.py

!python /content/drive/MyDrive/stella_mb2-master/assertDataset.py

!python /content/models/research/object_detection/model_main_tf2.py --model_dir=train/ --pipeline_config_path=/content/drive/MyDrive/stella_mb2-master/network/ssd/pipeline.config --num_train_steps=50000

!python /content/models/research/object_detection/export_tflite_graph_tf2.py     --trained_checkpoint_dir /content/drive/MyDrive/train     --output_directory /content/drive/MyDrive/stella_mb2-master/network/ssd/saved_model     --pipeline_config_path /content/drive/MyDrive/stella_mb2-master/network/ssd/pipeline.config

!python /content/drive/MyDrive/stella_mb2-master/quanti.py

!python /content/drive/MyDrive/stella_mb2-master/detect_saved.py

!python /content/drive/MyDrive/stella_mb2-master/detect.py