# -*- coding: utf-8 -*-
"""video_capture.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FCKOfZ9rN0v45owt0L4gAgrOaZlBkHkm
"""

import cv2

from google.colab import drive
drive.mount('/content/drive')

video = cv2.VideoCapture("drive/MyDrive/recording/pecora.avi")
i = 1
while True:
  i=i+1
  ret,frame = video.read()
  cv2.imwrite("drive/MyDrive/frame/pecora/pecora"+str(i)+".jpg",frame)

i